import type { NextApiRequest, NextApiResponse } from 'next';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // 返回79只已发行REITs数据
  const mockProducts = [
    // 上海证券交易所 - 508开头
    {
      reit_code: '508000.SH',
      reit_short_name: '华安张江产业园REIT',
      fund_manager: '华安基金管理有限公司',
      asset_manager: '上海张江（集团）有限公司',
      operator: '上海张江（集团）有限公司',
      listing_date: '2021-06-21',
      fund_size: 5.00,
      total_assets: 50.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '508001.SH',
      reit_short_name: '浙商沪杭甬REIT',
      fund_manager: '浙商基金管理有限公司',
      asset_manager: '浙江沪杭甬高速公路股份有限公司',
      operator: '浙江沪杭甬高速公路股份有限公司',
      listing_date: '2021-06-21',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 25.5,
    },
    {
      reit_code: '508002.SH',
      reit_short_name: '华安百联消费REIT',
      fund_manager: '华安基金管理有限公司',
      asset_manager: '上海百联集团股份有限公司',
      operator: '上海百联集团股份有限公司',
      listing_date: '2021-12-14',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 30.0,
    },
    {
      reit_code: '508003.SH',
      reit_short_name: '中金联东科创REIT',
      fund_manager: '中金基金管理有限公司',
      asset_manager: '联东集团有限公司',
      operator: '联东集团有限公司',
      listing_date: '2021-12-14',
      fund_size: 7.50,
      total_assets: 75.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '508005.SH',
      reit_short_name: '华夏首创奥莱REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '首创城发集团',
      operator: '首创钜大',
      listing_date: '2021-12-14',
      fund_size: 12.00,
      total_assets: 120.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '508006.SH',
      reit_short_name: '富国首创水务REIT',
      fund_manager: '富国基金管理有限公司',
      asset_manager: '首创环保集团',
      operator: '首创环保集团',
      listing_date: '2021-12-14',
      fund_size: 18.50,
      total_assets: 185.0,
      asset_type_national: '生态环保基础设施',
      asset_type_csrc: '污水处理',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 30.0,
    },
    {
      reit_code: '508007.SH',
      reit_short_name: '中金山東高速REIT',
      fund_manager: '中金基金管理有限公司',
      asset_manager: '山东高速集团',
      operator: '山东高速集团',
      listing_date: '2021-12-14',
      fund_size: 30.00,
      total_assets: 300.0,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 25.0,
    },
    {
      reit_code: '508008.SH',
      reit_short_name: '国金中国铁建REIT',
      fund_manager: '国金基金管理有限公司',
      asset_manager: '中国铁建股份有限公司',
      operator: '中国铁建股份有限公司',
      listing_date: '2021-12-14',
      fund_size: 47.93,
      total_assets: 479.3,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 28.5,
    },
    {
      reit_code: '508009.SH',
      reit_short_name: '中金安徽交控REIT',
      fund_manager: '中金基金管理有限公司',
      asset_manager: '安徽省交通控股集团有限公司',
      operator: '安徽省交通控股集团有限公司',
      listing_date: '2021-12-14',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 26.0,
    },
    {
      reit_code: '508010.SH',
      reit_short_name: '中金重庆两江REIT',
      fund_manager: '中金基金管理有限公司',
      asset_manager: '重庆两江新区开发投资集团有限公司',
      operator: '重庆两江新区开发投资集团有限公司',
      listing_date: '2021-12-14',
      fund_size: 36.00,
      total_assets: 360.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.5,
    },
    {
      reit_code: '508011.SH',
      reit_short_name: '嘉实物美消费REIT',
      fund_manager: '嘉实基金管理有限公司',
      asset_manager: '物美科技集团有限公司',
      operator: '物美科技集团有限公司',
      listing_date: '2021-12-14',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '508012.SH',
      reit_short_name: '招商科创REIT',
      fund_manager: '招商基金管理有限公司',
      asset_manager: '招商局蛇口工业区控股股份有限公司',
      operator: '招商局蛇口工业区控股股份有限公司',
      listing_date: '2021-12-14',
      fund_size: 15.00,
      total_assets: 150.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 27.5,
    },
    {
      reit_code: '508015.SH',
      reit_short_name: '中信建投明阳智能新能源REIT',
      fund_manager: '中信建投基金管理有限公司',
      asset_manager: '明阳智慧能源集团股份有限公司',
      operator: '明阳智慧能源集团股份有限公司',
      listing_date: '2022-06-28',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '清洁能源基础设施',
      asset_type_csrc: '风电',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 30.0,
    },
    {
      reit_code: '508016.SH',
      reit_short_name: '华夏华电清洁能源REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '华电新能源集团股份有限公司',
      operator: '华电新能源集团股份有限公司',
      listing_date: '2022-06-28',
      fund_size: 25.00,
      total_assets: 250.0,
      asset_type_national: '清洁能源基础设施',
      asset_type_csrc: '光伏',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '508017.SH',
      reit_short_name: '华夏金茂商业REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '中国金茂控股集团有限公司',
      operator: '中国金茂控股集团有限公司',
      listing_date: '2022-06-28',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.5,
    },
    {
      reit_code: '508018.SH',
      reit_short_name: '华夏中国交建REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '中国交通建设股份有限公司',
      operator: '中国交通建设股份有限公司',
      listing_date: '2022-06-28',
      fund_size: 93.99,
      total_assets: 939.9,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 27.0,
    },
    {
      reit_code: '508019.SH',
      reit_short_name: '中金湖北科投光谷REIT',
      fund_manager: '中金基金管理有限公司',
      asset_manager: '武汉光谷建设投资有限公司',
      operator: '武汉光谷建设投资有限公司',
      listing_date: '2022-06-28',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '508021.SH',
      reit_short_name: '国泰海通临港创新产业园REIT',
      fund_manager: '国泰基金管理有限公司',
      asset_manager: '上海临港经济发展（集团）有限公司',
      operator: '上海临港经济发展（集团）有限公司',
      listing_date: '2022-06-28',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '508022.SH',
      reit_short_name: '博时津开产园REIT',
      fund_manager: '博时基金管理有限公司',
      asset_manager: '天津经济技术开发区',
      operator: '天津经济技术开发区',
      listing_date: '2022-06-28',
      fund_size: 15.00,
      total_assets: 150.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.5,
    },
    {
      reit_code: '508026.SH',
      reit_short_name: '嘉实中国电建清洁能源REIT',
      fund_manager: '嘉实基金管理有限公司',
      asset_manager: '中国电力建设集团有限公司',
      operator: '中国电力建设集团有限公司',
      listing_date: '2022-09-29',
      fund_size: 15.00,
      total_assets: 150.0,
      asset_type_national: '清洁能源基础设施',
      asset_type_csrc: '水电',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 30.0,
    },
    {
      reit_code: '508027.SH',
      reit_short_name: '东吴苏园产业REIT',
      fund_manager: '东吴基金管理有限公司',
      asset_manager: '苏州工业园区股份有限公司',
      operator: '苏州工业园区股份有限公司',
      listing_date: '2022-09-29',
      fund_size: 30.00,
      total_assets: 300.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '508028.SH',
      reit_short_name: '中信建投国家电投新能源REIT',
      fund_manager: '中信建投基金管理有限公司',
      asset_manager: '国家电力投资集团有限公司',
      operator: '国家电力投资集团有限公司',
      listing_date: '2022-09-29',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '清洁能源基础设施',
      asset_type_csrc: '风电',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.5,
    },
    {
      reit_code: '508029.SH',
      reit_short_name: '中信建投沈阳国际软件园REIT',
      fund_manager: '中信建投基金管理有限公司',
      asset_manager: '沈阳国际软件园有限公司',
      operator: '沈阳国际软件园有限公司',
      listing_date: '2022-09-29',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.5,
    },
    {
      reit_code: '508031.SH',
      reit_short_name: '国泰海通城投宽庭保租房REIT',
      fund_manager: '国泰基金管理有限公司',
      asset_manager: '上海城投控股股份有限公司',
      operator: '上海城投控股股份有限公司',
      listing_date: '2022-12-09',
      fund_size: 30.00,
      total_assets: 300.0,
      asset_type_national: '保障性租赁住房',
      asset_type_csrc: '保障性租赁住房',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 25.0,
    },
    {
      reit_code: '508033.SH',
      reit_short_name: '易方达深高速REIT',
      fund_manager: '易方达基金管理有限公司',
      asset_manager: '深圳高速公路股份有限公司',
      operator: '深圳高速公路股份有限公司',
      listing_date: '2022-12-09',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 27.0,
    },

    // 深圳证券交易所 - 180开头
    {
      reit_code: '180101.SZ',
      reit_short_name: '博时蛇口产园REIT',
      fund_manager: '博时基金管理有限公司',
      asset_manager: '招商局蛇口工业区控股股份有限公司',
      operator: '招商局蛇口工业区控股股份有限公司',
      listing_date: '2021-06-21',
      fund_size: 9.00,
      total_assets: 90.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '180102.SZ',
      reit_short_name: '华夏合肥高新REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '合肥高新技术产业开发区',
      operator: '合肥高新技术产业开发区',
      listing_date: '2021-06-21',
      fund_size: 15.00,
      total_assets: 150.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '180103.SZ',
      reit_short_name: '华夏和达高科REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '杭州和达高科集团有限公司',
      operator: '杭州和达高科集团有限公司',
      listing_date: '2021-06-21',
      fund_size: 12.00,
      total_assets: 120.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.5,
    },
    {
      reit_code: '180105.SZ',
      reit_short_name: '易方达广开产园REIT',
      fund_manager: '易方达基金管理有限公司',
      asset_manager: '广州开发区控股集团有限公司',
      operator: '广州开发区控股集团有限公司',
      listing_date: '2021-06-21',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '180106.SZ',
      reit_short_name: '广发成都高投产业园REIT',
      fund_manager: '广发基金管理有限公司',
      asset_manager: '成都高投资产经营管理有限公司',
      operator: '成都高投资产经营管理有限公司',
      listing_date: '2021-06-21',
      fund_size: 15.00,
      total_assets: 150.0,
      asset_type_national: '产业园区基础设施',
      asset_type_csrc: '产业园区',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '180201.SZ',
      reit_short_name: '平安广州广河REIT',
      fund_manager: '平安基金管理有限公司',
      asset_manager: '广州交通投资集团有限公司',
      operator: '广州交通投资集团有限公司',
      listing_date: '2021-06-21',
      fund_size: 91.14,
      total_assets: 911.4,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 25.0,
    },
    {
      reit_code: '180202.SZ',
      reit_short_name: '华夏越秀高速REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '越秀交通基建有限公司',
      operator: '越秀交通基建有限公司',
      listing_date: '2021-12-14',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 26.5,
    },
    {
      reit_code: '180203.SZ',
      reit_short_name: '招商高速公路REIT',
      fund_manager: '招商基金管理有限公司',
      asset_manager: '招商局公路网络科技控股股份有限公司',
      operator: '招商局公路网络科技控股股份有限公司',
      listing_date: '2021-12-14',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '交通基础设施',
      asset_type_csrc: '收费公路',
      product_structure: '公募REITs',
      duration_years: 99,
      leverage_ratio: 27.0,
    },
    {
      reit_code: '180301.SZ',
      reit_short_name: '红土创新盐田港REIT',
      fund_manager: '红土创新基金管理有限公司',
      asset_manager: '盐田港集团',
      operator: '盐田港集团',
      listing_date: '2021-06-21',
      fund_size: 18.40,
      total_assets: 184.0,
      asset_type_national: '仓储物流基础设施',
      asset_type_csrc: '仓储物流',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 30.0,
    },
    {
      reit_code: '180302.SZ',
      reit_short_name: '华夏深国际REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '深圳国际控股有限公司',
      operator: '深圳国际控股有限公司',
      listing_date: '2021-12-14',
      fund_size: 15.00,
      total_assets: 150.0,
      asset_type_national: '仓储物流基础设施',
      asset_type_csrc: '仓储物流',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '180303.SZ',
      reit_short_name: '华泰宝湾物流REIT',
      fund_manager: '华泰基金管理有限公司',
      asset_manager: '宝湾物流控股有限公司',
      operator: '宝湾物流控股有限公司',
      listing_date: '2021-12-14',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '仓储物流基础设施',
      asset_type_csrc: '仓储物流',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '180305.SZ',
      reit_short_name: '南方顺丰物流REIT',
      fund_manager: '南方基金管理有限公司',
      asset_manager: '顺丰控股股份有限公司',
      operator: '顺丰控股股份有限公司',
      listing_date: '2021-12-14',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '仓储物流基础设施',
      asset_type_csrc: '仓储物流',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.5,
    },
    {
      reit_code: '180306.SZ',
      reit_short_name: '华夏安博仓储REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '安博（中国）投资有限公司',
      operator: '安博（中国）投资有限公司',
      listing_date: '2022-06-28',
      fund_size: 15.00,
      total_assets: 150.0,
      asset_type_national: '仓储物流基础设施',
      asset_type_csrc: '仓储物流',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 30.0,
    },
    {
      reit_code: '180401.SZ',
      reit_short_name: '鹏华深圳能源REIT',
      fund_manager: '鹏华基金管理有限公司',
      asset_manager: '深圳能源集团股份有限公司',
      operator: '深圳能源集团股份有限公司',
      listing_date: '2021-12-14',
      fund_size: 35.38,
      total_assets: 353.8,
      asset_type_national: '生态环保基础设施',
      asset_type_csrc: '垃圾焚烧及生物质发电',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 30.0,
    },
    {
      reit_code: '180402.SZ',
      reit_short_name: '工银蒙能清洁能源REIT',
      fund_manager: '工银瑞信基金管理有限公司',
      asset_manager: '内蒙古能源发电投资集团有限公司',
      operator: '内蒙古能源发电投资集团有限公司',
      listing_date: '2022-06-28',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '清洁能源基础设施',
      asset_type_csrc: '光伏',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '180501.SZ',
      reit_short_name: '红土创新深圳安居REIT',
      fund_manager: '红土创新基金管理有限公司',
      asset_manager: '深圳市人才安居集团有限公司',
      operator: '深圳市人才安居集团有限公司',
      listing_date: '2021-12-14',
      fund_size: 25.00,
      total_assets: 250.0,
      asset_type_national: '保障性租赁住房',
      asset_type_csrc: '保障性租赁住房',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 25.0,
    },
    {
      reit_code: '180502.SZ',
      reit_short_name: '招商基金蛇口租赁住房REIT',
      fund_manager: '招商基金管理有限公司',
      asset_manager: '招商局蛇口工业区控股股份有限公司',
      operator: '招商局蛇口工业区控股股份有限公司',
      listing_date: '2022-06-28',
      fund_size: 13.00,
      total_assets: 130.0,
      asset_type_national: '保障性租赁住房',
      asset_type_csrc: '保障性租赁住房',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 26.0,
    },
    {
      reit_code: '180601.SZ',
      reit_short_name: '华夏华润商业REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '华润置地有限公司',
      operator: '华润置地有限公司',
      listing_date: '2022-12-09',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '180602.SZ',
      reit_short_name: '中金印力消费REIT',
      fund_manager: '中金基金管理有限公司',
      asset_manager: '印力集团',
      operator: '印力集团',
      listing_date: '2022-12-09',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '180603.SZ',
      reit_short_name: '华夏大悦城商业REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '大悦城控股集团股份有限公司',
      operator: '大悦城控股集团股份有限公司',
      listing_date: '2022-12-09',
      fund_size: 33.92,
      total_assets: 339.2,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.5,
    },
    {
      reit_code: '180605.SZ',
      reit_short_name: '易方达华威市场REIT',
      fund_manager: '易方达基金管理有限公司',
      asset_manager: '华威商贸集团有限公司',
      operator: '华威商贸集团有限公司',
      listing_date: '2022-12-09',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
    {
      reit_code: '180606.SZ',
      reit_short_name: '中金中国绿发商业REIT',
      fund_manager: '中金基金管理有限公司',
      asset_manager: '中国绿发投资集团有限公司',
      operator: '中国绿发投资集团有限公司',
      listing_date: '2023-03-24',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.0,
    },
    {
      reit_code: '180607.SZ',
      reit_short_name: '华夏中海商业REIT',
      fund_manager: '华夏基金管理有限公司',
      asset_manager: '中国海外发展有限公司',
      operator: '中国海外发展有限公司',
      listing_date: '2023-03-24',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '消费基础设施',
      asset_type_csrc: '消费基础设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 27.5,
    },
    {
      reit_code: '180701.SZ',
      reit_short_name: '银华绍兴原水水利REIT',
      fund_manager: '银华基金管理有限公司',
      asset_manager: '绍兴市原水集团有限公司',
      operator: '绍兴市原水集团有限公司',
      listing_date: '2023-03-24',
      fund_size: 20.00,
      total_assets: 200.0,
      asset_type_national: '生态环保基础设施',
      asset_type_csrc: '水利设施',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 30.0,
    },
    {
      reit_code: '180801.SZ',
      reit_short_name: '中航首钢绿能REIT',
      fund_manager: '中航基金管理有限公司',
      asset_manager: '首钢集团',
      operator: '首钢集团',
      listing_date: '2021-06-21',
      fund_size: 13.38,
      total_assets: 133.8,
      asset_type_national: '生态环保基础设施',
      asset_type_csrc: '垃圾焚烧及生物质发电',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 28.5,
    },
    {
      reit_code: '180901.SZ',
      reit_short_name: '南方润泽科技数据中心REIT',
      fund_manager: '南方基金管理有限公司',
      asset_manager: '润泽科技发展有限公司',
      operator: '润泽科技发展有限公司',
      listing_date: '2023-03-24',
      fund_size: 10.00,
      total_assets: 100.0,
      asset_type_national: '新基建',
      asset_type_csrc: '数据中心',
      product_structure: '公募REITs',
      duration_years: 20,
      leverage_ratio: 29.0,
    },
  ];

  // 为每个产品添加行情数据（模拟）
  const productsWithQuotes = mockProducts.map((product) => {
    // 模拟随机生成行情数据
    const issuePrice = product.fund_size / (product.total_assets / 100);
    const changePercent = (Math.random() * 10 - 5).toFixed(2); // -5% 到 +5%
    const change = (issuePrice * parseFloat(changePercent) / 100).toFixed(2);
    const price = (issuePrice + parseFloat(change)).toFixed(2);
    const open = (parseFloat(price) * (0.98 + Math.random() * 0.04)).toFixed(2);
    const volume = Math.floor(Math.random() * 10000000 + 1000000); // 100万到1100万
    const turnoverRate = (Math.random() * 5).toFixed(2); // 0-5%

    return {
      ...product,
      code: product.reit_code,
      name: product.reit_short_name,
      issuePrice: parseFloat(issuePrice.toFixed(2)),
      quote: {
        price: parseFloat(price),
        prevClose: parseFloat(issuePrice.toFixed(2)),
        open: parseFloat(open),
        change: parseFloat(change),
        changePercent: parseFloat(changePercent),
        volume: volume,
        turnoverRate: parseFloat(turnoverRate),
      },
    };
  });

  return res.status(200).json({
    success: true,
    data: productsWithQuotes,
    count: productsWithQuotes.length,
  });
}
